services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ebanx_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - CACHE_STORE=file
